---
- name: configtest v2ray
  command: /usr/bin/v2ray/v2ray -test -config=/etc/v2ray/config.json
  register: v2ray_configtest_result

- name: restart v2ray
  service:
    name: v2ray
    state: restarted
  when: v2ray_configtest_result is succeeded
